spring.datasource.url=jdbc:mysql://db-music-mysql-ian8979.d.aivencloud.com:27111/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_8qlVW2606XsmqVjj0Ci

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
